CREATE TABLE IF NOT EXISTS test_users (
  id VARCHAR(18) NOT NULL
  , value VARCHAR(255) DEFAULT NULL
  , created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
  , updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  , PRIMARY KEY(id)
);

